import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import {spawn} from 'node:child_process'
import {pathToFileURL} from 'node:url'
import {makeHomeFixture,mockHome,ref,wallpaperId,wallpaperBytes} from './d09_home_fixture.mjs'
const root=path.resolve(import.meta.dirname,'../..'),output=path.join(root,'artifacts/d09-home-browser')
await fs.mkdir(output,{recursive:true})
const {chromium}=await import(pathToFileURL(process.env.NEVOLIUM_PLAYWRIGHT_MODULE).href)
const server=spawn(path.join(root,'apps/web/node_modules/.bin/vite'),['preview','--host','127.0.0.1','--port','4199','--strictPort'],{cwd:path.join(root,'apps/web'),stdio:'ignore'})
let browser,stage='start';const results=[]
async function eventually(test,message){for(let i=0;i<100;i++){if(await test())return;await new Promise(r=>setTimeout(r,100))}throw Error(message)}
try{
 await eventually(async()=>{try{return(await fetch('http://127.0.0.1:4199')).ok}catch{return false}},'preview unavailable')
 browser=await chromium.launch({headless:true,executablePath:process.env.NEVOLIUM_CHROMIUM_EXECUTABLE||undefined,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']})
 for(const [name,width,height] of [['desktop',1440,1000],['tablet',820,1180],['phone',390,844]]){
  stage=name+':load';console.log(stage)
  const state=makeHomeFixture(),context=await browser.newContext({viewport:{width,height},locale:'fr-FR',serviceWorkers:'block'})
  await mockHome(context,state);const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('http://127.0.0.1:4199');const home=page.locator('.home-browser:visible')
  const choose=async id=>{
   const target=home.locator(`.spatial-workspace [data-node="${id}"]`)
   await target.waitFor()
   if(await home.locator('.home-item-details').count())await home.getByRole('button',{name:'Fermer la fiche',exact:true}).click()
   await target.click()
  }
  const openDisplay=async()=>{
   const display=home.locator('.spatial-display')
   await display.locator('summary').waitFor()
   if(await display.getAttribute('open')===null)await display.locator('summary').click()
  }
  const chooseView=async label=>{await openDisplay();await home.getByRole('button',{name:label,exact:true}).click()}
  await home.getByRole('heading',{name:'Votre Mycelium',exact:true}).waitFor()
  assert.equal(await home.locator('.home-section-heading').getByRole('button',{name:'Personnaliser mon accueil',exact:true}).count(),0,'Personalisation must not remain a separate heading action')
  const spatial=home.locator('.spatial-workspace')
  if(name==='phone')assert.equal(await spatial.getAttribute('data-spatial-view'),'2d')
  else{
   await home.locator('.spatial-viewport canvas').waitFor()
   await eventually(async()=>JSON.parse(await home.locator('.spatial-viewport').getAttribute('data-spatial-metrics')||'{}').frames>1,'3D frames missing')
   const surface=await home.locator('.spatial-viewport').boundingBox()
   assert(surface.x===0&&surface.y===0&&surface.width===width&&surface.height===height,`${name}: Mycelium must fill the desktop, without a separate frame`)
   assert.equal(await home.locator('.spatial-viewport canvas').evaluate(el=>el.getContext('webgl2').getContextAttributes().alpha),true,'Canvas must preserve the wallpaper alpha channel')
   assert.equal(await home.locator('.spatial-viewport canvas').evaluate(el=>{const gl=el.getContext('webgl2');return gl.getParameter(gl.COLOR_CLEAR_VALUE)[3]}),0,'Empty space must remain transparent, not just support alpha')
   assert.equal(await home.locator('.spatial-viewport').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)')
   const canvas=await home.locator('.spatial-viewport canvas').boundingBox()
   assert(Math.abs(canvas.width-surface.width)<4&&Math.abs(canvas.height-surface.height)<4,`${name}: renderer must fill its viewport`)
   assert.equal(await spatial.getAttribute('data-spatial-view'),'3d')
   await eventually(async()=>{
    const labels=await home.locator('.spatial-labels button').all()
    return labels.length===6&&(await Promise.all(labels.map(label=>label.isVisible()))).every(Boolean)
   },`${name}: the initial overview must show every entry point in the six-node home fixture`)
   await openDisplay()
   assert.equal(await home.locator('.spatial-display > summary').getAttribute('aria-label'),'Affichage : 3D')
   await home.getByRole('button',{name:'Animer le réseau',exact:true}).click()
   assert.equal(await home.locator('.spatial-viewport').getAttribute('data-spatial-reduced-motion'),'true')
   await home.getByRole('button',{name:'Animer le réseau',exact:true}).click()
   await home.locator('.spatial-display > summary').click()
  }
  await page.screenshot({path:path.join(output,`${name}-home.png`)})
  // Accessible list has the same objects and is also the no-WebGL navigation surface.
  await chooseView('Vue 2D')
  await eventually(()=>[...state.layouts.keys()].some(key=>key.startsWith(`mycelium.home.${name}.camera.`)),`${name}: the view preference must use a device-class workspace`)
  stage=name+':transversal';console.log(stage)
  await choose(ref('project:recherche'))
  await home.locator('.home-item-details .home-relations li').first().waitFor()
  assert.equal(await page.evaluate(()=>document.activeElement.classList.contains('home-item-details')),true,'Selection focuses its readable details')
  await page.keyboard.press('Escape')
  assert.equal(await home.locator('.home-item-details').count(),0,'Escape closes the details')
  assert.equal(await page.evaluate(()=>document.activeElement.dataset.node),ref('project:recherche'),'Escape restores keyboard navigation')
  await choose(ref('project:recherche'))
  if(name!=='phone'){
   await chooseView('Vue 3D')
   await home.locator('.spatial-viewport canvas').waitFor()
   await home.locator('.spatial-viewport canvas').evaluate(el=>window.__homeCanvas=el)
   await home.getByRole('button',{name:'Ouvrir',exact:true}).click()
   await page.locator('.cockpit-home-button').waitFor()
   assert.equal(await page.locator('.home-browser .spatial-toolbar').count(),0,'Home display controls must leave the DOM while a tool is open')
   assert.equal(await page.locator('.home-browser').getAttribute('inert'),'')
   assert.equal(await page.locator('.home-browser .spatial-viewport').getAttribute('data-spatial-background'),'true')
   assert.equal(await page.locator('.home-browser .spatial-viewport canvas').evaluate(el=>el===window.__homeCanvas),true,'Opening a tool must not replace the home renderer')
   await page.locator('.cockpit-home-button').click()
   await home.locator('.spatial-display > summary').waitFor()
   assert.equal(await home.locator('.spatial-viewport canvas').evaluate(el=>el===window.__homeCanvas),true,'Returning preserves the renderer and its camera')
   await home.locator('.home-item-details h2').getByText('EXEMPLE — Recherche — atelier fictif',{exact:true}).waitFor()
  }
  await home.getByRole('button',{name:'Explorer les liens',exact:true}).click()
  await chooseView('Vue 2D')
  await choose(ref('document:recherche-2'))
  await home.getByRole('button',{name:'Explorer les liens',exact:true}).click()
  await chooseView('Vue 2D')
  await choose(ref('document:crypto-2'))
  await home.getByRole('button',{name:'Explorer les liens',exact:true}).click()
  await eventually(async()=>(await home.locator('.home-item-details h2').textContent())==='Hypothèse de concentration','cross-project focus missing')
  await home.getByRole('button',{name:'Épingler à l’accueil',exact:true}).click()
  await eventually(()=>state.layouts.get('mycelium.home.navigation').layout.entries.some(e=>e.ref===ref('document:crypto-2')),'pin not persisted')
  if(name!=='phone')await eventually(async()=>JSON.parse(await home.locator('.spatial-viewport').getAttribute('data-spatial-metrics')||'{}').frames>1,'transversal 3D frames missing')
  await page.screenshot({path:path.join(output,`${name}-transversal.png`)})
  await home.getByRole('button',{name:'Accueil',exact:true}).click()
  stage=name+':file';console.log(stage)
  await chooseView('Vue 2D')
  await choose('folder:sources')
  await chooseView('Vue 2D')
  await choose(ref('asset:recherche-observations.csv'))
  const download=page.waitForEvent('download')
  await home.getByRole('button',{name:'Télécharger le fichier',exact:true}).click()
  const received=await download
  assert.deepEqual(await fs.readFile(await received.path()),await fs.readFile(path.join(root,'examples/mycelium/recherche/observations.csv')))
  await home.getByRole('button',{name:'Explorer les liens',exact:true}).click()
  await chooseView('Vue 2D')
  await choose(ref('project:recherche'))
  await home.getByRole('button',{name:'Explorer les liens',exact:true}).click()
  await chooseView('Vue 2D')
  await choose(ref('asset:recherche-parcours.svg'))
  await home.getByRole('button',{name:'Afficher l’aperçu',exact:true}).click()
  await home.locator('.home-file-preview').waitFor()
  await eventually(async()=>home.locator('.home-file-preview').evaluate(img=>img.complete&&img.naturalWidth>0),'SVG preview missing')
  await home.getByRole('button',{name:'Accueil',exact:true}).click()
  stage=name+':customize';console.log(stage)
  await openDisplay()
  await home.getByRole('button',{name:'Personnaliser mon accueil',exact:true}).click()
  const editor=home.locator('.home-customize')
  await editor.getByLabel('Couleur du fond',{exact:true}).fill('#153948')
  await eventually(()=>state.layouts.get('mycelium.home.navigation').layout.background?.color==='#153948','background colour not saved')
  await editor.getByLabel('Choisir une image',{exact:true}).setInputFiles({name:'desktop.png',mimeType:'image/png',buffer:wallpaperBytes})
  await eventually(()=>state.layouts.get('mycelium.home.navigation').layout.background?.assetId===wallpaperId,'background asset not saved')
  assert(state.wallpaperUpload.includes(wallpaperBytes),'Upload must contain the original image')
  assert(!JSON.stringify(state.layouts.get('mycelium.home.navigation')).includes('blob:'),'Object URLs must never persist')
  await editor.locator('.home-organization > summary').click()
  await editor.getByLabel('Nom du dossier',{exact:true}).first().fill('À vérifier')
  await editor.getByRole('button',{name:'Créer le dossier',exact:true}).click()
  await eventually(()=>state.layouts.get('mycelium.home.navigation').layout.folders.some(f=>f.label==='À vérifier'),'folder not saved')
  await editor.getByLabel('Nom du raccourci 1',{exact:true}).fill('Mon laboratoire')
  const folderId=state.layouts.get('mycelium.home.navigation').layout.folders.find(f=>f.label==='À vérifier').id
  await editor.getByLabel('Dossier 1',{exact:true}).selectOption(folderId)
  await editor.getByRole('button',{name:'Descendre 1',exact:true}).click()
  await eventually(()=>state.layouts.get('mycelium.home.navigation').layout.entries[1].label==='Mon laboratoire','order not saved')
  await editor.getByRole('button',{name:'Annuler la dernière modification',exact:true}).click()
  await eventually(()=>state.layouts.get('mycelium.home.navigation').layout.entries[0].label==='Mon laboratoire','undo not saved')
  state.failSave=true
  await editor.getByLabel('Nom du raccourci 1',{exact:true}).fill('Mon labo')
  await editor.getByRole('button',{name:'Réessayer la sauvegarde',exact:true}).click()
  await eventually(()=>state.layouts.get('mycelium.home.navigation').layout.entries[0].label==='Mon labo','retry failed')
  await editor.getByRole('button',{name:'Terminé',exact:true}).click()
  await page.reload();await home.getByRole('heading',{name:'Votre Mycelium',exact:true}).waitFor()
  await eventually(()=>home.locator('.desktop-wallpaper').getAttribute('data-wallpaper-loaded').then(value=>value==='true'),'private wallpaper not restored after reload')
  await chooseView('Vue 2D')
  await choose(`folder:${folderId}`)
  await chooseView('Vue 2D')
  await home.locator(`.spatial-workspace [data-node="${ref('project:recherche')}"]`).getByText('Mon labo',{exact:true}).waitFor()
  assert.equal(state.nodes.get(ref('project:recherche')).label,'EXEMPLE — Recherche — atelier fictif','Shortcut rename mutated canonical data')
  // Language changes only UI copy; example content stays as authored.
  await page.getByRole('button',{name:'English',exact:true}).click()
  await home.getByRole('heading',{name:'Your Mycelium',exact:true}).waitFor()
  await openDisplay()
  await home.getByRole('button',{name:'Customize my home',exact:true}).waitFor()
  assert.equal(await home.locator('.spatial-display > summary').getAttribute('aria-label'),'Display : 2D')
  assert(!await home.getByRole('button',{name:'Personnaliser mon accueil',exact:true}).count())
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`${name}: horizontal overflow`)
  await page.screenshot({path:path.join(output,`${name}-personal-home-en.png`)})
  assert.deepEqual(errors,[])
  // A removed file must leave a usable solid background and a truthful message.
  state.wallpaperUnavailable=true
  await page.reload();await home.getByText('Your background image is unavailable. Your chosen colour is displayed.',{exact:true}).waitFor()
  assert.equal(await home.locator('.desktop-wallpaper').getAttribute('data-wallpaper-loaded'),'false')
  results.push({device:name,sharedRenderer:name==='phone'?'2D default':'3D default',transparentDesktop:name!=='phone',toolReturnContext:name!=='phone',immediateRelations:true,keyboardReturn:true,privateWallpaper:true,missingWallpaperFallback:true,transversal:true,privateLayout:true,folders:true,order:true,undo:true,saveRetry:true,reload:true,locale:true,fileBytes:true,svgPreview:true})
  await context.close()
 }
 await fs.writeFile(path.join(output,'qualification.json'),JSON.stringify({status:'passed',corpus:'mycelium-example-v1',results},null,2))
 console.log('D09 HOME BROWSER PASS',JSON.stringify(results))
}catch(error){
 await fs.writeFile(path.join(output,'failure.json'),JSON.stringify({stage,error:String(error)},null,2))
 const page=browser?.contexts().at(-1)?.pages().at(-1)
 if(page){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true});await fs.writeFile(path.join(output,'failure.html'),await page.content())}
 throw error
}
finally{await browser?.close();server.kill()}
